namespace Fabulous.Avalonia

open System
open System.Collections
open System.Runtime.CompilerServices
open Avalonia.Controls
open Avalonia.Controls.Primitives
open Avalonia.Media
open Fabulous
open Fabulous.Avalonia
open Fabulous.Avalonia.Mvu
open Fabulous.StackAllocatedCollections

type IFabMvuDataGrid =
    inherit IFabMvuTemplatedControl
    inherit IFabDataGrid

module MvuDataGrid =
    let Columns =
        MvuAttributes.defineAvaloniaNonGenericListWidgetCollection "DataGrid_Columns" (fun target -> (target :?> DataGrid).Columns :> IList)

    let HorizontalScroll =
        Attributes.defineEvent "DataGrid_HorizontalScroll" (fun target -> (target :?> DataGrid).HorizontalScroll)

    let VerticalScroll =
        Attributes.defineEvent "DataGrid_VerticalScroll" (fun target -> (target :?> DataGrid).VerticalScroll)

    let AutoGeneratingColumn =
        Attributes.defineEvent "DataGrid_AutoGeneratingColumn" (fun target -> (target :?> DataGrid).AutoGeneratingColumn)

    let BeginningEdit =
        Attributes.defineEvent "DataGrid_BeginningEdit" (fun target -> (target :?> DataGrid).BeginningEdit)

    let CellEditEnded =
        Attributes.defineEvent "DataGrid_CellEditEnded" (fun target -> (target :?> DataGrid).CellEditEnded)

    let CellEditEnding =
        Attributes.defineEvent "DataGrid_CellEditEnding" (fun target -> (target :?> DataGrid).CellEditEnding)

    let CellPointerPressed =
        Attributes.defineEvent "DataGrid_CellPointerPressed" (fun target -> (target :?> DataGrid).CellPointerPressed)

    let ColumnDisplayIndexChanged =
        Attributes.defineEvent "DataGrid_ColumnDisplayIndexChanged" (fun target -> (target :?> DataGrid).ColumnDisplayIndexChanged)

    let ColumnReordered =
        Attributes.defineEvent "DataGrid_ColumnReordered" (fun target -> (target :?> DataGrid).ColumnReordered)

    let ColumnReordering =
        Attributes.defineEvent "DataGrid_ColumnReordering" (fun target -> (target :?> DataGrid).ColumnReordering)

    let CurrentCellChanged =
        Attributes.defineEvent "DataGrid_CurrentCellChanged" (fun target -> (target :?> DataGrid).CurrentCellChanged)

    let LoadingRow =
        Attributes.defineEvent "DataGrid_LoadingRow" (fun target -> (target :?> DataGrid).LoadingRow)

    let PreparingCellForEdit =
        Attributes.defineEvent "DataGrid_PreparingCellForEdit" (fun target -> (target :?> DataGrid).PreparingCellForEdit)

    let RowEditEnded =
        Attributes.defineEvent "DataGrid_RowEditEnded" (fun target -> (target :?> DataGrid).RowEditEnded)

    let RowEditEnding =
        Attributes.defineEvent "DataGrid_RowEditEnding" (fun target -> (target :?> DataGrid).RowEditEnding)

    let SelectionChanged =
        Attributes.defineEvent<SelectionChangedEventArgs> "DataGrid_SelectionChanged" (fun target -> (target :?> DataGrid).SelectionChanged)

    let Sorting =
        Attributes.defineEvent "DataGrid_Sorting" (fun target -> (target :?> DataGrid).Sorting)

    let UnloadingRow =
        Attributes.defineEvent "DataGrid_UnloadingRow" (fun target -> (target :?> DataGrid).UnloadingRow)

    let LoadingRowDetails =
        Attributes.defineEvent "DataGrid_LoadingRowDetails" (fun target -> (target :?> DataGrid).LoadingRowDetails)

    let RowDetailsVisibilityChanged =
        Attributes.defineEvent "DataGrid_RowDetailsVisibilityChanged" (fun target -> (target :?> DataGrid).RowDetailsVisibilityChanged)

    let UnloadingRowDetails =
        Attributes.defineEvent "DataGrid_UnloadingRowDetails" (fun target -> (target :?> DataGrid).UnloadingRowDetails)


[<AutoOpen>]
module MvuDataGridBuilders =
    type Fabulous.Avalonia.Mvu.View with

        /// <summary>Creates a DataGrid widget.</summary>
        /// <param name="items">The items to display.</param>
        static member DataGrid(items: #IEnumerable) =
            WidgetBuilder<'msg, IFabMvuDataGrid>(DataGrid.WidgetKey, DataGrid.Items.WithValue(items), DataGrid.AutoGeneratedColumns.WithValue(true))

        /// <summary>Creates a CustomDataGrid widget.</summary>
        /// <param name="items">The items to display.</param>
        static member CustomDataGrid(items: #IEnumerable) =
            CollectionBuilder<'msg, IFabMvuDataGrid, IFabMvuDataGridColumn>(DataGrid.WidgetKey, MvuDataGrid.Columns, DataGrid.Items.WithValue(items))

type MvuDataGridModifiers =
    /// <summary>Listens to the HorizontalScroll Scroll event.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="fn">Raised when the HorizontalScroll value changes.</param>
    [<Extension>]
    static member inline onHorizontalScroll(this: WidgetBuilder<'msg, IFabMvuDataGrid>, fn: ScrollEventArgs -> 'msg) =
        this.AddScalar(MvuDataGrid.HorizontalScroll.WithValue(fn))

    /// <summary>Listens to the VerticalScroll Scroll event.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="fn">Raised when the VerticalScroll value changes.</param>
    [<Extension>]
    static member inline onVerticalScroll(this: WidgetBuilder<'msg, IFabMvuDataGrid>, fn: ScrollEventArgs -> 'msg) =
        this.AddScalar(MvuDataGrid.VerticalScroll.WithValue(fn))

    /// <summary>Listens to the AutoGeneratingColumn event.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="fn">Raised when a column is auto generated.</param>
    [<Extension>]
    static member inline onAutoGeneratingColumn(this: WidgetBuilder<'msg, IFabMvuDataGrid>, fn: DataGridAutoGeneratingColumnEventArgs -> 'msg) =
        this.AddScalar(MvuDataGrid.AutoGeneratingColumn.WithValue(fn))

    /// <summary>Listens to the BeginningEdit event.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="fn">Raised when a cell or row begins editing.</param>
    [<Extension>]
    static member inline onBeginningEdit(this: WidgetBuilder<'msg, IFabMvuDataGrid>, fn: DataGridBeginningEditEventArgs -> 'msg) =
        this.AddScalar(MvuDataGrid.BeginningEdit.WithValue(fn))

    /// <summary>Listens to the CellEditEnded event.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="fn">Raised when a cell edit has ended.</param>
    [<Extension>]
    static member inline onCellEditEnded(this: WidgetBuilder<'msg, IFabMvuDataGrid>, fn: DataGridCellEditEndedEventArgs -> 'msg) =
        this.AddScalar(MvuDataGrid.CellEditEnded.WithValue(fn))

    /// <summary>Listens to the CellEditEnding event.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="fn">Raised when a cell edit is ending.</param>
    [<Extension>]
    static member inline onCellEditEnding(this: WidgetBuilder<'msg, IFabMvuDataGrid>, fn: DataGridCellEditEndingEventArgs -> 'msg) =
        this.AddScalar(MvuDataGrid.CellEditEnding.WithValue(fn))

    /// <summary>Listens to the CellPointerPressed event.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="fn">Raised when a cell is clicked.</param>
    [<Extension>]
    static member inline onCellPointerPressed(this: WidgetBuilder<'msg, IFabMvuDataGrid>, fn: DataGridCellPointerPressedEventArgs -> 'msg) =
        this.AddScalar(MvuDataGrid.CellPointerPressed.WithValue(fn))

    /// <summary>Listens to the ColumnDisplayIndexChanged event.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="fn">Raised when a column's DisplayIndex changes.</param>
    [<Extension>]
    static member inline onColumnDisplayIndexChanged(this: WidgetBuilder<'msg, IFabMvuDataGrid>, fn: DataGridColumnEventArgs -> 'msg) =
        this.AddScalar(MvuDataGrid.ColumnDisplayIndexChanged.WithValue(fn))

    /// <summary>Listens to the ColumnReordered event.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="fn">Raised when a column is reordered.</param>
    [<Extension>]
    static member inline onColumnReordered(this: WidgetBuilder<'msg, IFabMvuDataGrid>, fn: DataGridColumnEventArgs -> 'msg) =
        this.AddScalar(MvuDataGrid.ColumnReordered.WithValue(fn))

    /// <summary>Listens to the ColumnReordering event.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="fn">Raised when a column is being reordered.</param>
    [<Extension>]
    static member inline onColumnReordering(this: WidgetBuilder<'msg, IFabMvuDataGrid>, fn: DataGridColumnReorderingEventArgs -> 'msg) =
        this.AddScalar(MvuDataGrid.ColumnReordering.WithValue(fn))

    /// <summary>Listens to the CurrentCellChanged event.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="fn">Raised when the current cell changes.</param>
    [<Extension>]
    static member inline onCurrentCellChanged(this: WidgetBuilder<'msg, IFabMvuDataGrid>, fn: EventArgs -> 'msg) =
        this.AddScalar(MvuDataGrid.CurrentCellChanged.WithValue(fn))

    /// <summary>Listens to the LoadingRow event.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="fn">Raised when a row is loading.</param>
    [<Extension>]
    static member inline onLoadingRow(this: WidgetBuilder<'msg, IFabMvuDataGrid>, fn: DataGridRowEventArgs -> 'msg) =
        this.AddScalar(MvuDataGrid.LoadingRow.WithValue(fn))

    /// <summary>Listens to the PreparingCellForEdit event.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="fn">Raised when a cell is being prepared for editing.</param>
    [<Extension>]
    static member inline onPreparingCellForEdit(this: WidgetBuilder<'msg, IFabMvuDataGrid>, fn: DataGridPreparingCellForEditEventArgs -> 'msg) =
        this.AddScalar(MvuDataGrid.PreparingCellForEdit.WithValue(fn))

    /// <summary>Listens to the RowEditEnded event.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="fn">Raised when a row edit has ended.</param>
    [<Extension>]
    static member inline onRowEditEnded(this: WidgetBuilder<'msg, IFabMvuDataGrid>, fn: DataGridRowEditEndedEventArgs -> 'msg) =
        this.AddScalar(MvuDataGrid.RowEditEnded.WithValue(fn))

    /// <summary>Listens to the RowEditEnding event.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="fn">Raised when a row edit is ending.</param>
    [<Extension>]
    static member inline onRowEditEnding(this: WidgetBuilder<'msg, IFabMvuDataGrid>, fn: DataGridRowEditEndingEventArgs -> 'msg) =
        this.AddScalar(MvuDataGrid.RowEditEnding.WithValue(fn))

    /// <summary>Listens to the SelectionChanged event.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="fn">Raised when the selection changes.</param>
    [<Extension>]
    static member inline onSelectionChanged(this: WidgetBuilder<'msg, IFabMvuDataGrid>, fn: SelectionChangedEventArgs -> 'msg) =
        this.AddScalar(MvuDataGrid.SelectionChanged.WithValue(fn))

    /// <summary>Listens to the Sorting event.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="fn">Raised when the data is being sorted.</param>
    [<Extension>]
    static member inline onSorting(this: WidgetBuilder<'msg, IFabMvuDataGrid>, fn: DataGridColumnEventArgs -> 'msg) =
        this.AddScalar(MvuDataGrid.Sorting.WithValue(fn))

    /// <summary>Listens to the UnloadingRow event.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="fn">Raised when a row is unloading.</param>
    [<Extension>]
    static member inline onUnloadingRow(this: WidgetBuilder<'msg, IFabMvuDataGrid>, fn: DataGridRowEventArgs -> 'msg) =
        this.AddScalar(MvuDataGrid.UnloadingRow.WithValue(fn))

    /// <summary>Listens to the LoadingRowDetails event.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="fn">Raised when a row details is loading.</param>
    [<Extension>]
    static member inline onLoadingRowDetails(this: WidgetBuilder<'msg, IFabMvuDataGrid>, fn: DataGridRowDetailsEventArgs -> 'msg) =
        this.AddScalar(MvuDataGrid.LoadingRowDetails.WithValue(fn))

    /// <summary>Listens to the RowDetailsVisibilityChanged event.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="fn">Raised when a row details visibility changes.</param>
    [<Extension>]
    static member inline onRowDetailsVisibilityChanged(this: WidgetBuilder<'msg, IFabMvuDataGrid>, fn: DataGridRowDetailsEventArgs -> 'msg) =
        this.AddScalar(MvuDataGrid.RowDetailsVisibilityChanged.WithValue(fn))

    /// <summary>Listens to the UnloadingRowDetails event.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="fn">Raised when a row details is unloading.</param>
    [<Extension>]
    static member inline onUnloadingRowDetails(this: WidgetBuilder<'msg, IFabMvuDataGrid>, fn: DataGridRowDetailsEventArgs -> 'msg) =
        this.AddScalar(MvuDataGrid.UnloadingRowDetails.WithValue(fn))

type DataGridExtraModifiers =
    /// <summary>Sets the HorizontalGridLinesBrush property.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="value">The HorizontalGridLinesBrush value.</param>
    [<Extension>]
    static member inline horizontalGridLinesBrush(this: WidgetBuilder<'msg, IFabMvuDataGrid>, value: Color) =
        DataGridModifiers.horizontalGridLinesBrush(this, View.SolidColorBrush(value))

    /// <summary>Sets the HorizontalGridLinesBrush property.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="value">The HorizontalGridLinesBrush value.</param>
    [<Extension>]
    static member inline horizontalGridLinesBrush(this: WidgetBuilder<'msg, IFabMvuDataGrid>, value: string) =
        DataGridModifiers.horizontalGridLinesBrush(this, View.SolidColorBrush(Color.Parse(value)))

    /// <summary>Sets the RowBackground property.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="value">The RowBackground value.</param>
    [<Extension>]
    static member inline rowBackground(this: WidgetBuilder<'msg, IFabMvuDataGrid>, value: Color) =
        DataGridModifiers.rowBackground(this, View.SolidColorBrush(value))

    /// <summary>Sets the RowBackground property.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="value">The RowBackground value.</param>
    [<Extension>]
    static member inline rowBackground(this: WidgetBuilder<'msg, IFabMvuDataGrid>, value: string) =
        DataGridModifiers.rowBackground(this, View.SolidColorBrush(Color.Parse(value)))

    /// <summary>Sets the VerticalGridLinesBrush property.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="value">The VerticalGridLinesBrush value.</param>
    [<Extension>]
    static member inline verticalGridLinesBrush(this: WidgetBuilder<'msg, IFabMvuDataGrid>, value: Color) =
        DataGridModifiers.verticalGridLinesBrush(this, View.SolidColorBrush(value))

    /// <summary>Sets the VerticalGridLinesBrush property.</summary>
    /// <param name="this">Current widget.</param>
    /// <param name="value">The VerticalGridLinesBrush value.</param>
    [<Extension>]
    static member inline verticalGridLinesBrush(this: WidgetBuilder<'msg, IFabMvuDataGrid>, value: string) =
        DataGridModifiers.verticalGridLinesBrush(this, View.SolidColorBrush(Color.Parse(value)))

type MvuDataGridCollectionBuilderExtensions =
    [<Extension>]
    static member inline Yield<'msg, 'marker, 'itemType when 'msg: equality and 'itemType :> IFabMvuDataGridColumn>
        (_: CollectionBuilder<'msg, 'marker, IFabMvuDataGridColumn>, x: WidgetBuilder<'msg, 'itemType>)
        : Content<'msg> =
        { Widgets = MutStackArray1.One(x.Compile()) }

    [<Extension>]
    static member inline Yield<'msg, 'marker, 'itemType when 'msg: equality and 'itemType :> IFabMvuDataGridColumn>
        (_: CollectionBuilder<'msg, 'marker, IFabMvuDataGridColumn>, x: WidgetBuilder<'msg, Memo.Memoized<'itemType>>)
        : Content<'msg> =
        { Widgets = MutStackArray1.One(x.Compile()) }
